### ISSUE TITLE
sigterm does not stop the consumer

### ISSUE THREAD

**Issue by felipevolpone** [sceneryback/kafka-best-practices#4] opened 2021-04-27 13:56 UTC
Hi @sceneryback, first of all: thank you very much for these examples. They're very, very useful.

While running it, I was not able to make the `consumer.Close()` really stop and exit the program (I was not running with `go run`) while using the `StartMultiAsyncConsumer`. The program receives the `fmt.Println("received signal", <-c)`, but it does not really stop the consumer.

I've even tried to changed the code to use a `sync.WaitGroup` to coordinate the goroutines reading from the bufChan to stop, but even with that the consumer.Close hangs forever and it does not stop. Do you have any clue why?

Is mostly like this:
```golang
ctx, cancel := context.WithCancel(context.Background())
wg := &sync.WaitGroup{}

consumer, err := StartMultiAsyncConsumer(ctx, wg, cfg)
if err != nil {
panic(err)
}

sigterm := make(chan os.Signal, 1)
signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)

select {
case <-ctx.Done():
log.Println("terminating: context cancelled")
case <-sigterm:
log.Println("terminating: via signal")
cancel()
wg.Wait()
consumer.Close() // it hangs forever and never finishes the program
}
```

I wonder if its really a problem to do not call `consumer.Close` (I've read the sarama code, but it's unclear if not calling it would lead to message losses or something like that).

**Comment by sceneryback** [comment] 2021-04-30 03:55
Hi @felipevolpone, thanks for your attention and tests. But I really cannot reproduce your case. I suspect there are other blocking issues in your code. Hope for more details.

I added some debug logs like the following:

![image](https://user-images.githubusercontent.com/11677736/116643029-bddb6400-a9a2-11eb-92c5-88533219a4a5.png)

And use code that you provided like:
```
ctx, cancel := context.WithCancel(context.Background())
wg := &sync.WaitGroup{}

consumer, err := consumer.StartMultiAsyncConsumer(broker, topic)
if err != nil {
	panic(err)
}

sigterm := make(chan os.Signal, 1)
signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)
fmt.Println("received signal", <-sigterm)

select {
case <-ctx.Done():
	log.Println("terminating: context cancelled")
case <-sigterm:
	log.Println("terminating: via signal")
	cancel()
	wg.Wait()
	consumer.Close() // it hangs forever and never finishes the program
	log.Println("consumer stopped")
}
```

Then pressed Ctrl+C. From the output, it received signal at 2021-04-30 10:41:43:

![image](https://user-images.githubusercontent.com/11677736/116643106-ebc0a880-a9a2-11eb-9d75-edeb6338d420.png)

And after one second, it called consumer.Close() and exited:

![image](https://user-images.githubusercontent.com/11677736/116643203-16aafc80-a9a3-11eb-937b-f730af06aa10.png)

Reading from bufChan is still working while consumer is closing, so there are 3 more messages after the logs as you can see.

At last, calling consumer.Close() is necessary since in fact it tells kafka that it will exit then kafka can release resources efficiently.

**Closed as completed** 2021-05-29 16:17 UTC

**Comment by felipevolpone** [comment] 2021-05-31 20:53
Hey, thank you very much for your attention and quick answer. You're right, the problem was on my end.

Again, ty for this project :)
